apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t39rii5qr-python
  janus-idp.io/tekton: t39rii5qr-python
  backstage.io/kubernetes-id: t39rii5qr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t39rii5qr-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
